#!/bin/bash
# =============================================================
# post-review.sh — Copilot Hook Script (postToolUse)
# =============================================================
# Runs after the Copilot agent uses a tool (e.g., edits a file).
# Purpose: Format code and append review report links.
#
# This hook:
#   1. Runs Prettier to format any changed files
#   2. Runs ESLint for quick lint checks
#   3. Appends a timestamped entry to the findings report
#
# Hook context is passed via stdin as JSON.
# Exit 0 = allow the action to proceed.
# Exit non-zero = block the action.
# =============================================================
set -euo pipefail

# Read hook context from stdin (JSON payload from Copilot)
INPUT=$(cat)

# Create logs directory if it doesn't exist
mkdir -p logs/copilot
mkdir -p samples/findings

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# --- Step 1: Run formatter (if available) ---
if command -v npx &> /dev/null; then
  # Only format if prettier is available in the project
  if [ -f "node_modules/.bin/prettier" ] || npx prettier --version &> /dev/null 2>&1; then
    echo "🔧 Running Prettier formatter..."
    npx prettier --write "sample-app/**/*.js" 2>/dev/null || true
  fi

  # Run ESLint if available
  if [ -f "node_modules/.bin/eslint" ] || npx eslint --version &> /dev/null 2>&1; then
    echo "🔍 Running ESLint..."
    npx eslint "sample-app/**/*.js" --no-error-on-unmatched-pattern 2>/dev/null || true
  fi
fi

# --- Step 2: Log the hook execution ---
echo "{\"timestamp\":\"$TIMESTAMP\",\"event\":\"postToolUse\",\"action\":\"format-and-lint\"}" >> logs/copilot/hooks.log

# --- Step 3: Append entry to findings report ---
REPORT_FILE="samples/findings/report.md"
if [ ! -f "$REPORT_FILE" ]; then
  echo "# Review & Security Report" > "$REPORT_FILE"
  echo "" >> "$REPORT_FILE"
  echo "Generated by Copilot hooks. Entries appended after each tool use." >> "$REPORT_FILE"
  echo "" >> "$REPORT_FILE"
fi

echo "---" >> "$REPORT_FILE"
echo "### Post-Review Hook — $TIMESTAMP" >> "$REPORT_FILE"
echo "- Formatter: Prettier (auto-format applied)" >> "$REPORT_FILE"
echo "- Linter: ESLint (quick check completed)" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

echo "✅ Post-review hook completed"
exit 0
